name: Holmes Matrix Test
on: 
  workflow_dispatch:
  pull_request:

jobs:
  test-holmes:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python_version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        spacy_version: ['3.4.1']
        click_version: ['8.0.1']
        include:
          - os: 'ubuntu-latest'
            python_version: '3.9'
            spacy_version: '3.5.0'
            click_version: '8.0.1'
          - os: 'ubuntu-latest'
            python_version: '3.9'
            spacy_version: '3.3.1'
            click_version: '8.0.1'
          - os: 'ubuntu-latest'
            python_version: '3.9'
            spacy_version: '3.2.4'
            click_version: '8.0.1'
          - os: 'ubuntu-latest'
            python_version: '3.9'
            spacy_version: '3.1.6'
            click_version: '7.1.2'
    runs-on: ${{ matrix.os }}
    steps:

    - name: Increase swap file size on Windows
      if: ${{ matrix.os == 'windows-latest' }}
      uses: al-cheb/configure-pagefile-action@v1.2
      with:
        minimum-size: 64GB
        maximum-size: 64GB

    - name: Checkout repository code
      uses: actions/checkout@v3
      with:
          ref: master

    - name: Initialize Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python_version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install spacy==${{ matrix.spacy_version }} pytest spacy-lookups-data
        
        # see https://github.com/explosion/spaCy/issues/10564
        pip uninstall click -y
        pip install "click==${{ matrix.click_version }}"

    - name: Install spaCy models
      run: |
        python -m spacy download en_core_web_sm
        python -m spacy download en_core_web_lg
        python -m spacy download en_core_web_trf
        python -m spacy download de_core_news_lg
        python -m spacy download pl_core_news_md

    - name: Install Coreferee
      run: |
        pip install coreferee
        python -m coreferee install en
        python -m coreferee install de
        python -m coreferee install pl

    - name: Install Holmes
      run: |
        cd ${{ github.workspace }}
        pip install .

    - name: Test Holmes
      run: |
        python -m pytest tests/de/test_doc_examples_DE.py
        python -m pytest tests/de/test_phraselet_production_DE.py
        python -m pytest tests/de/test_questions_DE.py
        python -m pytest tests/de/test_semantics_DE.py
        python -m pytest tests/de/test_structural_matching_DE.py
        python -m pytest tests/de/test_structural_matching_with_coreference_DE.py
        python -m pytest tests/de/test_supervised_topic_classification_DE.py
        python -m pytest tests/de/test_topic_matching_DE.py
        python -m pytest tests/en/test_doc_examples_EN.py
        python -m pytest tests/en/test_phraselet_production_EN.py
        python -m pytest tests/en/test_questions_EN.py
        python -m pytest tests/en/test_semantics_EN.py
        python -m pytest tests/en/test_structural_matching_EN.py
        python -m pytest tests/en/test_structural_matching_with_coreference_EN.py
        python -m pytest tests/en/test_supervised_topic_classification_EN.py
        python -m pytest tests/en/test_topic_matching_EN.py
        python -m pytest tests/common/test_manager.py
        python -m pytest tests/common/test_cpu_gpu.py
        python -m pytest tests/common/test_errors.py
        python -m pytest tests/common/test_ontology.py
        python -m pytest tests/common/test_serialization.py
        python -m pytest tests/common/test_word_level_matching.py
        python -m pytest tests/common/test_multithreading.py